### ISSUE TITLE
if piece is dragged and then released on original square, square should not be selected

### ISSUE THREAD

**Issue by isaacl** [ornicar/chessground#115]
Another edge case that can lead to accidental selection of a square:

If the user initiates a drag of a piece and moves it somewhere, but changes their mind and ends the drag back on the original square, the square is selected. Instead the square should not select.

**Comment by isaacl** [comment]
This one is still open!

The idea is that chessground should track if the drag moved far enough away from the original location, and if so, consider the mouse movement a drag and not a click. If the mouse is ultimately released on the original square, chessground should not select that square

**Comment by isaacl** [comment]
(But of course it’s not clear if we want this; I’m interested in your thoughts)

**Comment by ornicar** [comment]
Why not, if the implementation is cheap...
