### ISSUE TITLE
Racing Kings Analysis Board is Upside Down

### ISSUE THREAD

**Issue by landry314** [ornicar/chessground#122]
After a game of Racing Kings, click on the analysis button to open analysis and the board is upside down... quite simply...

You need to click on flip board to start to analyze the games.

This is true in the web browser and if I can recall correctly, in the Android app as well...

Oh, and this is not true DURING a correspondence game, only AFTER a game.

**Comment by gbtami** [comment]
This is not chessground problem. You should report it at https://github.com/ornicar/lila/issues

**Comment by landry314** [comment]
ok i opened it there...
