### ISSUE TITLE
bogus castling premove dests

### ISSUE THREAD

**Issue by niklasf** [ornicar/chessground#127]
![image](https://user-images.githubusercontent.com/402777/71616790-564bb380-2bb8-11ea-92bb-ef86b0a2d09c.png)

**Comment by gbtami** [comment]
I think this "fix" is partial only. Chessground should consider true castling availability of given position IMO.
![http://i.imgur.com/R8rX6Hc.png](http://i.imgur.com/R8rX6Hc.png)

**Comment by niklasf** [comment]
I guess we can at least check that the rook exists. Done (57a8524d44213afc0b6d81e63c3391e14aafa81a).

Actually checking castling rights and legality is out of scope.
