### ISSUE TITLE
pressing ALT (for blue arrow) opens browser menu in firefox

### ISSUE THREAD

**Issue by icp1994** [ornicar/chessground#128]
![2019-12-06 15 39 58 lichess org 37b2508532e8](https://user-images.githubusercontent.com/15713555/70315021-b57b0a00-183e-11ea-838c-3903dcc79095.png)

I've tested on my account and in a new private window. Pretty sure it was working at least two days ago

**Comment by icp1994** [comment]
hey @niklasf is there any workaround for this? really miss having four different markers/arrows for my studies :)

**Comment by niklasf** [comment]
Ok ... found an alternative (see #59). Will be in the next version.
