### ISSUE TITLE
HTML+JS+CSS example?

### ISSUE THREAD

**Issue by Nikola-Obreshkov** [ornicar/chessground#131]
Is there an example how to set up the chessground in an HTML page? There is a JS build:
https://github.com/ornicar/chessground/issues/62
also the basic CSS:
https://github.com/ornicar/chessground-examples/blob/master/assets/chessground.css
but I can find a basic example JSON config in order to run:
`var ground = Chessground(document.body, config);`
Is this possible?

**Comment by niklasf** [comment]
Something along these lines:
```html
<html>
<body>
<script src="chessground.js"></script>
<script>
var ground = Chessground(document.body, {});
</script>
</body>
</html>
```

**Comment by Nikola-Obreshkov** [comment]
This was the first I tried but it doesn't work. It shows an empty rectangle with notations. Only the drawing circles works.

**Comment by niklasf** [comment]
Make sure the stylesheet is also included. Check your developer console for requests to potentially missing images.

**Comment by Nikola-Obreshkov** [comment]
My questions is: Is there an example how to use this chess board with a simple HTML+JS+CSS+possible other assets? Otherwise it is just guessing: maybe there are not images, maybe there is svg asset missing, etc.

**Comment by honkskillet** [comment]
There is CSS missing.  Check out issue #134
