### ISSUE TITLE
Moved piece in move event

### ISSUE THREAD

**Issue by MrBr** [ornicar/chessground#135]
Is there a particular reason why moved piece isn't passed on move event?

Asking because I am having trouble formatting standard user notation where a piece is notated next to the square. I can achieve that outside the Chessground but it requires additional logic that doesn't look natural. It would be much simpler to just get piece information along with the move.

Do you have an alternative way to achieve that?

For the end, I would like to expand `move` handle with the moved piece but it would be a breaking change because the captured piece is already the third argument.  If you have an idea on how to do ir (or just don't mind the breaking change) let me know and I'll open a PR.

**Comment by niklasf** [comment]
It is not implemented because Lichess doesn't need it. But it does seem useful in general, so if it can be added without too much overhead, why not.

**Comment by niklasf** [comment]
`chessground.state.pieces[dest]` should be good enough.

**Comment by MrBr** [comment]
@niklasf thanks for the feedback! I had a hunch it's handled somehow.
