### ISSUE TITLE
Uncaught TypeError: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by jfily** [ornicar/chessground#136]
Hi,

I'm trying to use chessground with webpack but I get an error when I load the page : 

![image](https://user-images.githubusercontent.com/10220170/84780382-cc689900-afe5-11ea-9fea-4e28515cfd20.png)

My js code is quite simple ...

```javascript
const ground = Chessground(document.body, {
    fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1"
});
```

Any idea why this happens ?

**Comment by niklasf** [comment]
Thanks for reporting. Which version from npm or which commit from this repository is it using?

**Comment by jfily** [comment]
I'm using chessground@7.6.12 (@latest) from npm

**Comment by jfily** [comment]
I found the problem...

It seems you extend Array prototype so did I and .... it's conflicting.

I'll give a look to methods you create to avoid this.

**Comment by niklasf** [comment]
I am not able to reproduce this with a plain

```html
<body>
<script src="node_modules/chessground/dist/chessground.min.js"></script>
<script>
const ground = Chessground(document.body, {
  fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1"
});
</script>
</body>
```

Are you sure the test case is complete? What is producing the other wierd output in your screenshot?

**Comment by jfily** [comment]
The output comes from few methods I created :
 
```typescript
// Shuffle array
Array.prototype.shuffle = function () {
    const array = this.slice();
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * array.length);
        const temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
    return array;
};

// Unique values
Array.prototype.unique = function () {
    return [...new Set(this)];
};

// Last value
Array.prototype.last = function () {
    return this[this.length - 1];
};
```

But I don't see where this could conflict with chessground...

**Comment by jfily** [comment]
Looks like there is a problem when Array prototype is extended.

![image](https://user-images.githubusercontent.com/10220170/84784575-c6c18200-afea-11ea-8630-5a7d8f6059e6.png)

![image](https://user-images.githubusercontent.com/10220170/84784548-bdd0b080-afea-11ea-85f9-cc9773b9bd36.png)

**Comment by niklasf** [comment]
There are multiple places where chessground uses `for (const i in arr) { ...` to iterate over array indexes, without checking `hasOwnProperty`. So yeah ... chessground is not compatible with prototype extensions. Not sure if it's worth patching that for robustness, since that's a bad practice anyway.

**Comment by niklasf** [comment]
@jfily Looks like there were only two cases for arrays (https://github.com/ornicar/chessground/commit/b28d774c6cd0b04527ea42588b8b79bf1e4981ec), which were better served with `for of` loops anyway.

Many more cases for `Object.prototype`.
