### ISSUE TITLE
Drawing on the board stops working if the modifier key is released before the mouse

### ISSUE THREAD

**Issue by as-f** [ornicar/chessground#140]
**Problem:** If you draw on the board using modifier keys (eg shift) and you release the key before releasing the mouse, you get weird behavior, as if the mouse release didn't fully register.

**How to reproduce:**

1. Draw two arrows using a keyboard modifier, but release shift while still holding the mouse button down. If you move the mouse around now, the arrows don't move.
2. Release the mouse button.
3. Press shift and move the mouse around without clicking. The second arrow drawn follows the mouse.
4. Release shift and left click. Only the second arrow disappears. Clicking again removes all drawings.

**Expected behavior:**

- Left click should always clear all drawings.
- You should not be able to move arrows without clicking down on the mouse.

I'm not sure if you should be able to move arrows while still holding down the mouse button after having released modifier keys. My gut feeling is yes, you should be able to. That avoids weird edge cases like pressing new modifier keys midway though drawing an arrow.

I'd be happy to work on this and make a PR.

**Comment by niklasf** [comment]
Drawing with the right mouse button already works (and keeps the color) even after releasing the modifier, so I am all for making the left mouse button consistent.
