### ISSUE TITLE
Knight moves should be drawn as L arrows

### ISSUE THREAD

**Issue by enyo** [ornicar/chessground#149]
It would be great if knight moves could be drawn as L arrows instead of diagonals. I think that the way chess.com handles this is quite good: always draw an L shape if the arrow is 2 + 1 square.

**Comment by niklasf** [comment]
I much prefer the straight arrows.

**Comment by enyo** [comment]
How about adding this as an option, that could also be set in the settings on lichess.org?

**Comment by niklasf** [comment]
The bar for making new options is fairly high. I don't think this qualifies.
