### ISSUE TITLE
Extensions to other board sizes

### ISSUE THREAD

**Issue by eeegnu** [ornicar/chessground#154]
I've been working on a simple chess variant, and really wanted to integrate chessground for the graphics. The board dimensions are slightly different being 14x8 instead of 8x8 (as seen below, the idea there just being that it wraps around as a cylinder.) Could anyone who's familiar with this code base let me know if such modifications would be very difficult to make, or if it's as simple as changing a few functions. Another thought was to have two chessgrounds superimposed over each other to create the extra rows, and to use some trickery in sending pieces to the right place, but I don't know just how complex that would be.

![image](https://user-images.githubusercontent.com/36356950/94639367-06fef480-02aa-11eb-9383-ad9327457f25.png)

**Comment by ornicar** [comment]
We won't add anything to chessground that lichess.org doesn't use. You're welcome to fork it for your own needs.

**Comment by eeegnu** [comment]
I of course recognize this, I just wanted an opinion on if such a modification would entail a weeks long project, or a few hours long project.

**Comment by niklasf** [comment]
Maybe check out https://github.com/gbtami/chessgroundx.
