### ISSUE TITLE
Game review -> highlight move types on the board (blunder, mistake, best move, etc)

### ISSUE THREAD

**Issue by had3z** [ornicar/chessground#165]
Reason: when a user reviews his games, most of the time his eyes are on the board, not on the moves list. unless you shift your focus somewhere else(eval meter or moves list) there is no way to tell if your move was good or bad

example from chess.com 
![Screenshot](https://user-images.githubusercontent.com/8790301/105202362-96c2fa00-5b4a-11eb-971e-b94d34c72434.png)

**Comment by benediktwerner** [comment]
I think this can be closed now?

**Comment by had3z** [comment]
yes, this is the same as https://github.com/ornicar/lila/issues/8002
