### ISSUE TITLE
Replacing a piece on a square

### ISSUE THREAD

**Issue by void4** [ornicar/chessground#167]
Since this library doesn't implement promotion handling, and I don't want to create a new Chessground instance from the latest game FEN (for performance reasons and also because I want the move animations and no flickering while reloading), I need to replace a pawn when it promotes. How can I do this? Is there a set(square, piece, color) function? I don't see anything like it in the API.

**Comment by niklasf** [comment]
You can reconfigure the existing instance using https://github.com/ornicar/chessground/blob/972f71e466d27f1b2e86776fef2c8fee0ecb0dd0/src/api.ts#L12-L14. Just set a new FEN. It will compute the differences and make only the required chnages.
