### ISSUE TITLE
Specifying both fen and drawable.shapes does not actually show the shapes

### ISSUE THREAD

**Issue by DrPhil** [ornicar/chessground#171]
If you specify both shapes and fen in the initial config, the fen is honored but the shapes are not rendered. I could reproduce this on both Firefox (version 85) and Chromium (version 88). I am using chessground 7.9.3.

Here's the code:
```typescript
export const fromFen: Unit = {
  name: 'From FEN, from black POV without shapes',
  run(el) {
    return Chessground(el, {
      fen:'2r3k1/pp2Qpbp/4b1p1/3p4/3n1PP1/2N4P/Pq6/R2K1B1R w -',
      orientation: 'black'
    });
  }
};

export const fromFenWithShapes: Unit = {
  name: 'From FEN, from black POV with shapes',
  run(el) {
    return Chessground(el, {
      fen:'2r3k1/pp2Qpbp/4b1p1/3p4/3n1PP1/2N4P/Pq6/R2K1B1R w -',
      orientation: 'black',
      drawable: {shapes: [{
          orig: 'e4',
          brush: 'green'
        }]}
    });
  }
};

export const withoutFenWithShapes: Unit = {
  name: 'Without FEN, from black POV with shapes',
  run(el) {
    return Chessground(el, {
      orientation: 'black',
      drawable: {shapes: [{
          orig: 'e4',
          brush: 'green'
        }]}
    });
  }
};
```

Expected behavior: `fromFenWithShapes` looks the same as `fromFen` but with a green ring on e4.
Actual behavior:  `fromFenWithShapes` looks identical to `fromFen`.

Specifying the shapes programmatically with `setShapes` works as expected.

![image](https://user-images.githubusercontent.com/184889/107860687-f312f400-6e40-11eb-8836-c6c3b701e674.png)
![image](https://user-images.githubusercontent.com/184889/107860698-02923d00-6e41-11eb-946a-9a17b8abb9e2.png)
![image](https://user-images.githubusercontent.com/184889/107860703-09b94b00-6e41-11eb-9dc1-0a2cb718d5cd.png)

**Comment by DrPhil** [comment]
I don't understand if it is intentional. Removing [this line](
https://github.com/ornicar/chessground/blob/b403d05251614c95239ce642ce5b3896752e9531/src/config.ts#L101) fixes the issue for me, but I don't know if anyone else is relying on the current behavior.

**Comment by ornicar** [comment]
The idea was probably that the previous shapes no longer make sense on a new position. Calling setShapes is the way to go.
