### ISSUE TITLE
Dynamic column and row length

### ISSUE THREAD

**Issue by holgarsson** [ornicar/chessground#177]
Hello!

I've been enjoying playing around with this plugin for the last couple of months, creating some chess variations. 

At the moment, I want to change the constraints on the row/column length. At the moment it is fixed to 8x8. Is this something that can be changed without having to modify the core API?

Thank you!

**Comment by gbtami** [comment]
Try https://github.com/gbtami/chessgroundx

**Comment by holgarsson** [comment]
@gbtami Thanks! This is more or less the feature I'm looking for. Is there some way I can contact you? I have a few questions regarding your modifications
