### ISSUE TITLE
How to handle responsive sizing?

### ISSUE THREAD

**Issue by m-alzam** [ornicar/chessground#180]
Hi,

As I understand, the board container needs both the `width` and `height` CSS properties to be show properly. For example, try removing one of them in [this codepen](https://codepen.io/alcarazzam/pen/NWbJLNm) and it won't show properly.

But when I use the `max-width` property to make the board responsive on mobile devices, the board doesn't follow the width of the screen, it still has the same width as before.

I've tried using `aspect-ratio: 1 / 1` and it makes the board responsive, but [it doesn't show](https://codepen.io/alcarazzam/pen/abBMQde) in a CSS grid using using `justify-items: center`.

My question is: how to show a board that takes a maximum width and it's responsive for mobile devices?

Hope I explained my problem well.

Thanks.

**Comment by ArneVogel** [comment]
I solved the responsive sizing like this: https://github.com/ArneVogel/listudy/blob/master/assets/js/modules/ground.js#L38

Basically I take the maximum width possible for the container where the board should be shown and set that as the width of the container.

**Comment by gabrielbeauchemin** [comment]
Same question here. Ideally, I would like to use relative height and width. Example width: 50%, height 50%. Is there a way to make it work? Thanks!

**Comment by m-alzam** [comment]
Thanks @ArneVogel for the answer!

@gabrielbeauchemin, regarding your question, I think you can do it, but you need to use the trick that ArneVogel linked to make the board have the same width and height.
