### ISSUE TITLE
how to use it??

### ISSUE THREAD

**Issue by nishthaneeraj** [ornicar/chessground#183]
*I know I am asking a silly question but I am confused after installation that,*
_what is the file structure, and do we have to write only four lines for this???_
🥇 Any help would be appreciated 
Thanks in advance 👍

**Comment by gbtami** [comment]
See https://github.com/ornicar/chessground-examples

**Comment by nishthaneeraj** [comment]
> See https://github.com/ornicar/chessground-examples

I didn't get it.
