### ISSUE TITLE
opera missing release of right mouse button while drawing arrows

### ISSUE THREAD

**Issue by niklasf** [ornicar/chessground#190]
> In any game on Opera browser when trying to use the arrow for analysis, after clicking and holding the arrow appears, but after releasing the click the arrow continues to move with the mouse. Instead, the arrow should stay at the given square.
> 
> Browser: Opera 76.0.4017.154
> OS: Windows 10

from https://github.com/ornicar/lila/issues/9078. reproducible in browserstack. drawing arrows with shift and left mouse button not affected.

**Comment by benediktwerner** [comment]
This seems to be caused by some kind of mouse gesture system in Opera. As far as I can tell, it's not possible for websites to circumvent or disable this. The only solution is for users to disable it themselves in the settings.
