### ISSUE TITLE
y-axis wrong key in square on xiangqi

### ISSUE THREAD

**Issue by matamune94** [ornicar/chessground#194]
y-axis from top to bottom is currently : a: > a1 and i want change to a9 >  a0 , how can fix ?

**Comment by niklasf** [comment]
Hi, this should probably go to https://github.com/gbtami/chessgroundx.

**Comment by matamune94** [comment]
> Xin chào, điều này có thể truy cập https://github.com/gbtami/chessgroundx .

hi, i don't see the instructions anywhere
