### ISSUE TITLE
Problems with "npm" & "mithril"

### ISSUE THREAD

**Issue by LocutusOfPenguin** [ornicar/chessground#20]
Hi,
when i try to install the code (following the docu), i get an error concerning mithril

npm ERR! Error: No compatible version found: mithril@'github:ornicar/mithril.js#v0.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.2","0.1.3","0.1.4","0.1.12","0.1.13","0.1.0","0.1.16","0.1.17","0.1.18","0.1.19","0.1.20","0.1.21","0.1.22","0.1.23","0.1.24","0.1.25","0.1.26","0.1.27","0.1.28","0.1.29","0.1.30","0.1.31","0.1.32","0.1.33","0.1.34-beta.0","0.1.34","0.2.0"]

btw: i changed package.json from 1.0.0 to 0.2.0 but it doesnt work either way.
Not using npm at all, so please help what to do.
Thanks

**Comment by LocutusOfPenguin** [comment]
Just as a reminder:
My problem still exists :-(

**Comment by draconicfae** [comment]
I had the same issue.  It turned out that my version of npm was less than the minimum required.  You may need to bypass your package manager and install npm manually as I did.

**Comment by LocutusOfPenguin** [comment]
thx @draconicfae 
now working.
