### ISSUE TITLE
Automatic pawn promotion

### ISSUE THREAD

**Issue by victorocna** [ornicar/chessground#209]
Hello everyone!

I was wondering if it's possible to promote a pawn into any other piece.
From the API I noticed that `chess.move()` takes only `orig` and `dest` parameters. 
Is there any way to pass the new piece a pawn is promoted to?

Cheers,
Victor

**Comment by ornicar** [comment]
you can use https://github.com/ornicar/chessground/blob/master/src/api.ts#L30

**Comment by victorocna** [comment]
can you please give me an example of `setPieces` usage in javascript?

**Comment by victorocna** [comment]
Figured it out. An example for posterity below:

```js
setPieces({ a8: { role: 'queen', color: 'white', promoted: true } });
```

The only problem is that now the pawn that should be promoted does not disappear from the board.

**Comment by niklasf** [comment]
Include `a7: null`. Or alternatively just [`set({fen})`](https://github.com/ornicar/chessground/blob/master/src/api.ts#L14), and let chessground compute the incremental update.
