### ISSUE TITLE
Legal moves React error

### ISSUE THREAD

**Issue by victorocna** [ornicar/chessground#210]
Hello everyone!

I am implementing a chessboard "legal moves only" in React and I noticed that after chessground version `7.6.13` it stopped working.
For your convenience I made 2 codesandbox demo repos where you can see the problem:

- [working sandbox](https://codesandbox.io/s/chessground-legal-moves-e5jh8) for `chessground@7.6.13`
- [non-working sandbox](https://codesandbox.io/s/chessground-legal-moves-forked-8he93) for `chessground@latest`

The React implementation relies on [this function](https://github.com/ornicar/chessground-examples/blob/master/src/util.ts#L4) found in the examples repo.

Cheers!
Victor

**Comment by niklasf** [comment]
Hi, sorry, arguably this should have been a major version update. The issue becomes obvious when using types.

It's now:

```typescript
export type Dests = Map<Key, Key[]>;
```

So it should be:

```typescript
const dests = new Map();
// [...]
dests.set(s, ms.map((m) => m.to));
```

**Comment by victorocna** [comment]
Thanks for the explanation, I confirm that it works now for the latest package release. :+1:
