### ISSUE TITLE
Mistake in state.ts file

### ISSUE THREAD

**Issue by agawrylak** [ornicar/chessground#214]
Take a look at https://github.com/ornicar/chessground/blob/master/src/state.ts 
line 12 `check?: cg.Key; // square currently in check "a2" `
In fact it is not a cg.Key, it is a boolean. If you set it to true it will show red color under current player's king.

**Comment by benediktwerner** [comment]
You're looking at the wrong file. The config you're actually passing to chessground is here: https://github.com/ornicar/chessground/blob/master/src/config.ts#L11

And it has the correct type. What you linked is internal state of chessground which is different.
