### ISSUE TITLE
[Feature request] Custom Chess pieces

### ISSUE THREAD

**Issue by Pantyhose-X** [ornicar/chessground#217]
> * [ ] Rounded chess pieces
> * [ ] Chess pieces to Custom engraved text 

![image](https://user-images.githubusercontent.com/42504385/151115812-4d9d1ccd-2a0a-49d8-a8d2-05bfaab8cc6c.png)

**Comment by niklasf** [comment]
The piece set is already fully customizable with CSS. See https://github.com/ornicar/chessground/blob/master/assets/chessground.cburnett.css for a template with the default set. Additional sets are not part of this repository.
