### ISSUE TITLE
Tapping a square using Apple "Magic" Trackpad and potentially other tap based input device does not select the square

### ISSUE THREAD

**Issue by ferdinando-ferreira** [ornicar/chessground#24]
Greetings and, first of all, thanks for the amazing site and software. It is very much appreciated.
#### The Problem

As reported at [the forums](http://en.lichess.org/forum/lichess-feedback/feature-regression-in-the-last-update-touchpad-touchstart-doesnt-select-the-square) (admittedly the wrong place, just figured it out) there is a small but deadly regression on the handling of mouse events for some class of tap based input devices like Apple's [Magic trackpad](https://en.wikipedia.org/wiki/Magic_Trackpad) and others where tap to click is allowed.

The great majority of the players are not affected as it can't happen with a mouse but for the minority that players bullet in a touchpad having to drag or click instead of tap would be very limiting.

After opening a [game against the computer](http://en.lichess.org/47FZ22hqpXzC) in order to live debug the (minified) javascript in an attempt to figure out why it doesn't work I managed to isolate the problem and to find the cause.
#### The Probable Cause

The tap behaviour is implemented on Safari in a very similar way a normal mouse click. The former, like the later, consists (among other things) in one mousedown event followed by one mouseup event. 

But in the tap, as opposed to the click, there is no interval between the mouseup and the mousedown events, the mouseup fires up immediately after the mousedown leaving no time for anything in between.

As far as I could figure out the problem is that:
- the [start function](https://github.com/ornicar/chessground/blob/master/src/drag.js#L39) called by the [onstart event handler](https://github.com/ornicar/chessground/blob/master/src/view.js#L193) that handles the mousedown sets the value for draggable.current among other information about the current selected piece

and then
- passes the control to [ProcessDrag](https://github.com/ornicar/chessground/blob/master/src/drag.js#L57) that will, asynchronously (with the requestAnimationFrame call) try to determine over which square the selected piece is being held over 

and, at the same time asynchronously
- the [renderSquare function](https://github.com/ornicar/chessground/blob/master/src/view.js#L42) uses the information obtained by the above mentioned processes to determine how to draw the square, which squares are currently legal moves

until a mouseup, when
- the [end function](https://github.com/ornicar/chessground/blob/master/src/drag.js#L105) called by the [onend event handler](https://github.com/ornicar/chessground/blob/master/src/view.js#L207) that handles the mouseup that performs whatever action the player intended (or prevent it if it is not legal) and cleans up draggable.current along with the selection.

But in the case of the tap, as the mouseup happens right after the mousedown without any time for the requestAnimationFrame to execute once, draggable.current is cleaned up before ProcessDrag or renderSquare have the chance to use it and then processDrag stop calling itself recursively because cur.orig is now undefined.
#### A Potential Fix

I can't test it so I won't risk sending a PR but if I were to fix this my theory is that we need to ensure that that ProcessDrag is called at least once before mouseup so it can set the properties needed by the later to work properly, like this:

``` javascript
function processDragFrame(data) {
    var cur = data.draggable.current;
    if (cur.orig) {
      // cancel animations while dragging
      if (data.animation.current.start && data.animation.current.anims[cur.orig])
        data.animation.current = {};
      // if moving piece is gone, cancel
      if (hashPiece(data.pieces[cur.orig]) !== cur.piece) cancel(data);
      else {
        if (!cur.started && util.distance(cur.epos, cur.rel) >= data.draggable.distance)
          cur.started = true;
        if (cur.started) {
          cur.pos = [
            cur.epos[0] - cur.rel[0],
            cur.epos[1] - cur.rel[1]
          ];
          cur.over = board.getKeyAtDomPos(data, cur.epos, cur.bounds);
        }
      }
    }
    data.render();
    return cur.orig;
}

function processDrag(data) {
    if (processDragFrame(data)) {
        util.requestAnimationFrame(function() {
            processDrag(data);
        });
    }
}
```

This should be functionally equivalent to the original code except the main body of the function is executed at least once synchronously. 
#### Testing the Fix

Assuming there is an test environment I can help testing the fix, the steps are relatively simple:
1. To enter the test environment
2. Create a computer game
3. 1.e3

Let me know here or at lichess if I can be of any help.

Best regards

FF

**Comment by ornicar** [comment]
hopefully this is solved by the latest version - can be tested out on lichess.org
