### ISSUE TITLE
Changing board orientation does not redraw ranks and files

### ISSUE THREAD

**Issue by inoks** [ornicar/chessground#27]
`toggleOrientation()` method rotate the board, but keep ranks and files unchanged.

**Comment by dsjoerg** [comment]
maybe you have to call something else to redraw the labels?

**Comment by inoks** [comment]
Thanks @ornicar!

**Comment by inoks** [comment]
@ornicar just wonder, should updating orientation via:
`ground.set({orientation: 'black'})`
and 
`ground.set({orientation: 'white'})`
also trigger coords redraw (currently not)?

**Comment by ornicar** [comment]
yeah... it's all broken since I optimized the coords to render only once.

**Comment by inoks** [comment]
Ok, i use extra call `ground.data.redrawCoords(color);` as quick fix for it.
Thanks again!

**Comment by dsjoerg** [comment]
whoa @ornicar you are too fast!  i hadnt even posted my fiddle yet!   thank
you & respect.
