### ISSUE TITLE
Off-by-0.5-pixel offsets for square highlights

### ISSUE THREAD

**Issue by apetresc** [ornicar/chessground#28]
This is very minor, but quite annoying, and I'm not sure what the best way to fix it is. Basically, for most zoom levels, there is a good chance that the "selected" and "last move" overlays will be off by one pixel in either direction. As far as I can tell, it's because the piece overlay position is being calculated by CSS `transform`s, while the checkerboard background is simply a scaled image. So, when the final resolution doesn't evenly divide the scaling factor, it somehow interpolates the image to a resolution below 1 CSS pixel.

You end up with something like this:

![](http://i.imgur.com/rQhkHOK.png) (notice the bottom and right edges are off by one)

If I go into the Web Inspector and manually adjust the width and height of the square overlay from `12.5%` to `calc(12.5% + 1px)`, I end up with:

![](http://i.imgur.com/hBhqnLW.png) (now it's a bit too large, although _personally_ I find this error a bit less annoying)

I'm not sure how to fix this other than by replacing the board background image with all CSS-generated squares. Anyone have any clever ideas about this?

**Comment by ornicar** [comment]
This should be fixed now that lichess uses SVG boards.
