### ISSUE TITLE
square highlighting isn't perfectly aligned

### ISSUE THREAD

**Issue by isaacl** [ornicar/chessground#51]
It's more obvious with the grey premove overlay, but visible for green move highlights too.  In screenshot below, the green move highlight is not quite even with the bottom of `d5`.

My board zoom is at about 1/5 of the slider.

![image](https://cloud.githubusercontent.com/assets/1027886/23827332/6752d656-067f-11e7-92d8-d51c368c3da1.png)

**Comment by isaacl** [comment]
![image](https://cloud.githubusercontent.com/assets/1027886/23827389/dd35efec-0680-11e7-8be0-6a720f00b335.png)

**Comment by isaacl** [comment]
SVG rects are perfectly aligned -- let's switch highlight to position via svg:
```javascript
function renderSquare(pos: cg.Pos, bounds: ClientRect, style: string): SVGElement {
  const o = posToTranslate(pos, true, bounds);
  return setAttributes(createElement('rect'), {
    style: style,
    x: o[0],
    y: o[1],
    width: bounds.width / 8,
    height: bounds.height / 8
  });
}
```

**Comment by isaacl** [comment]
from opperwezen stream:
![image](https://user-images.githubusercontent.com/1027886/27549850-6cdbee6a-5a6b-11e7-875b-c025b7fcf476.png)

this would be nice to fix

**Comment by PureLines** [comment]
Any updates on this issue?

It’s ok in 7.5.1 version.

**Comment by niklasf** [comment]
It's ok in Crhome with the [rounding trick](https://backscattering.de/chess/display-table/), but still broken when using browser zoom or in other browsers.
