### ISSUE TITLE
Pieces do not resize with the board

### ISSUE THREAD

**Issue by KaeyangTheG** [ornicar/chessground#54]
Even with the resizable option set, the pieces do not scale or move in response to the board resizing.  Can an example of fluid layout be added to the examples.

**Comment by lakinwecker** [comment]
Yeah, I am experiencing the same issue.

**Comment by LocutusOfPenguin** [comment]
i use this:

$(window).resize(function() {
    chessground_1.redrawAll();
});

after that, i worked for me.

**Comment by ornicar** [comment]
This option does not mean what you think it does.

https://github.com/ornicar/chessground/blob/master/src/config.ts#L18

**Comment by lakinwecker** [comment]
So there is no bug? We are required to listen to resizes and call `redrawAll()`?

**Comment by ornicar** [comment]
run `document.body.dispatchEvent(new Event('chessground.resize'))` to make all chessground instances (with resizable=true) to recompute bounds and redraw.

**Comment by niklasf** [comment]
How about listening to `chessground.resize` unconditionally and to window `resize` with a flag? Are there performance concerns?

**Comment by ornicar** [comment]
There can be a lot of chessground instances on a page, and several events that can require redraw (like board zoom on lichess for instance).
