### ISSUE TITLE
Firefox: shift+right-click for arrows/circles gives a context menu after the circle is drawn

### ISSUE THREAD

**Issue by thomas-daniels** [ornicar/chessground#59]
Reporting at the right repository this time :)

**Comment by niklasf** [comment]
shift + right-click is intended as a way to forcibly open the context menu, even when the site disabled it. there have been workarounds, but i don't think anything can be done in the latest versions of firefox. perhaps we should add an alternative way to draw with red color.

**Comment by ProgramFOX** [comment]
Ctrl+Right-click and Ctrl+Alt+Right-click are still unused; those could be alternatives for red and orange.

**Comment by niklasf** [comment]
#126 adds an alternative method to get the same color. Nothing else we can do, here.

**Comment by niklasf** [comment]
There are 4 colors and plenty of modifiers (https://developer.mozilla.org/de/docs/Web/API/MouseEvent), but it looks like only one is usable in Firefox.

- ~altKey~ (opens the menu)
- ctrlKey
- ~metaKey~ (opens start menu on Windows)
- ~shiftKey~ (forces context menu)

So it's impossible ...

You could set `ui.key.menuAccessKey` to `0` in `about:config` to free up the ALT key (requires browser restart).

**Comment by niklasf** [comment]
Actually it may be possible to use AltGr on Windows and/or Meta on Mac. Will look into that ...
