### ISSUE TITLE
how to reach same as lichess/analysis with chess960?

### ISSUE THREAD

**Issue by LocutusOfPenguin** [ornicar/chessground#60]
Hi,
i have no idea for scala / and lila is quiet complex.

Now:
I changed the chess.js code so, it works for chess960, and i follow the example files with "playOtherSide".
But i cant get a castle correctly. If i have a bKd8, bRb8, and i click on the d8 square, i get c8 enlighted, but it will then make Kc8, not 0-0-0. On lichess the b8 square also shown as "capture", and lateron 0-0-0. 

How to reach this?
I mean, how do i change which squares are possible, when a user clicks on a square, and then lateron move it?

**Comment by niklasf** [comment]
Lichess adds a hook for `movable.events.after`, computes the new position (on the server) and updates the position (`chessground.set({fen})`).
