### ISSUE TITLE
Cancel a move?

### ISSUE THREAD

**Issue by legoboy0215** [ornicar/chessground#63]
I am using chess.js with this amazing chessboard. However, I can use the move event to validate the moves, but I do not know how to cancel an illegal move. How would I achieve that? (This isn't an issue, but I don't know where else to ask this, sorry)

cancelMove in the move event doesn't cancel the move, I've tried that. Or am I doing something wrong?

**Comment by ornicar** [comment]
cancelMove cancels the move being played, not the move played.

You should pass chessground the legal moves, so legal moves are highlighted, and illegal moves can't be played.

**Comment by legoboy0215** [comment]
Oh, thanks! BTW, how would I undo a move? I do want to perform server side validation so...

**Comment by ornicar** [comment]
Cancel on chess.js and apply the new FEN to chessground.

**Comment by legoboy0215** [comment]
Ah! Thanks again :)  Glad I moved away from chessboard.js after reading your post on reddit lol
