### ISSUE TITLE
ChessGround doesn't work on Epiphany and Midori Browsers

### ISSUE THREAD

**Issue by LocutusOfPenguin** [ornicar/chessground#64]
for our target plattform "RaspberryPi", these Browsers seems to be the standard (esp. Epiphany).
But it doesnt work for picochess...so, i tried it with "lichess.org" ..but there its same.

The start screen (with many diagrams) seems to work (despite the auto-update of moves), but if i click on one game, the board is broken (all pieces are at top left square).

see also this issue:https://github.com/jromang/picochess/issues/241

Since its not working on lichess and picochess, i guess its an internal problem of chessground.

**Comment by niklasf** [comment]
both of these browsers seem to support css 3 in their latest versions.

**Comment by LocutusOfPenguin** [comment]
ok, i dont use this (small) problem display anymore, and since
Raspbian now using Chromium - even Midori is working - this issue to be closed now.
