### ISSUE TITLE
Drawing text labels on top of chessground

### ISSUE THREAD

**Issue by jaxony** [ornicar/chessground#76]
Hi @ornicar, thanks for the amazing work on `chessground`! I'm making a chess-teaching app. Is there an easy way to add text labels (e.g. chess hints) next to specific chess pieces in `chessground`? Some very brief pointers on how this might be done would be greatly appreciated :-)

**Comment by ornicar** [comment]
You can either do it yourself from outside chessground, with absolute positioning, or fork chessground to add that logic.
