### ISSUE TITLE
Unable to render in horizontal mode

### ISSUE THREAD

**Issue by LgArcida** [ornicar/chessground#78]
I am trying to show a chessboard horizontally, default view is vertical. I tried rotating 90deg the parent container and chessboard scales accordingly. However, piece selection is completely wrong. As far as I can see the UI rotates but piece selection stays at top and bottom of the container.

**Comment by ornicar** [comment]
This is out of scope for chessground.

**Comment by ornicar** [comment]
Because of the way it computes which square was clicked based on cursor position. You'll have to fork chessground to make rotated boards work.
