### ISSUE TITLE
config.items not works

### ISSUE THREAD

**Issue by eshangin** [ornicar/chessground#88]
Hello. 

I tried to find a way how to add some custom items into the board. As I understand we have `config.items` for this. But the usage of this option is broken at the moment. Actually I do not see how we handle this option in the latest version of chessground.

BTW Liches successfully uses this option on https://lichess.org/learn. But 'learn' section uses `github:ornicar/chessground#v4.4.0`. I.e. older version. And v4 has some special code which handles config.items option https://github.com/ornicar/chessground/blob/v4/src/view.js#L170. The latest version of chessground do not have the same kind code.

**Comment by ornicar** [comment]
That's outside the scope of chessground since version 5. That was a leftover. You'll need to fork chessground for that usage.

**Comment by eshangin** [comment]
@ornicar OK, thanks for the info
