### ISSUE TITLE
chessground examples promotion bug

### ISSUE THREAD

**Issue by Simbaclaws** [ornicar/chessground#94]
Apparently when a pawn moves to the other side of the board aka (promotion), the game doesn't show a dialog to choose what the pawn should turn in to and the ai starts to switch it's team to the other side.
So whenever you get your pawn to the other side of the board, all of a sudden you're playing the other side.

This bug exists on version 7.3 since I couldn't get 7.6 to initialize the board at all, I don't know if this bug has been fixed ever since. If it has, can someone explain to me how I can get version 7.6 working? With perhaps an update of the example script? Since I can't seem to initialize the board in any way possible in version 7.6.

I think https://github.com/ornicar/chessground/issues/96 has the same issue for 7.6, at least, I am experiencing the same thing.

**Comment by niklasf** [comment]
chessground does not implement chess rules and does not come with a promotion dialog. These have to be implemented seperately.
