### ISSUE TITLE
Not able to make moves on mobile

### ISSUE THREAD

**Issue by ArneVogel** [ornicar/chessground#95]
Hi,

I am using chessground in my project here: https://github.com/ArneVogel/listudy , with this config https://github.com/ArneVogel/listudy/blob/master/app/src/utils/consts.js#L7

I myself and users have reported that its not possible to make moves on mobile. You cannot drag the pieces and click (touch one time) to make moves also doesnt work. After you click the legal moves show up for a split second but disappear before you can make the second click.

I am experiencing the same behavior with the [example repo](https://github.com/ornicar/chessground-examples).

Edit (browsers):
Samsung S8 using Chrome (tried Desktop Site) Android 9.0
Samsung J5 using Firefox
Using a desktop with Firefox mobile simulator

**Comment by niklasf** [comment]
Is this still an issue?

**Comment by ArneVogel** [comment]
Yes, nothing has changed.

**Comment by niklasf** [comment]
Looking at listudy, it doesn't appear to be using the latest version of chessground. Please start by updating. I can reproduce the issue on https://listudy.org/, but not in chessground-examples when using the latest chessground, nor on https://lichess.org/analysis.

**Comment by ArneVogel** [comment]
The latest chessground version (7.6.10) breaks for me https://i.imgur.com/lpWZFhA.png
No console errors are shown.

**Comment by niklasf** [comment]
Let's try to figure this out first. Is the base CSS up to date? There were some changes in the latest versions.

https://github.com/ornicar/chessground-examples/blob/master/assets/chessground.css

**Comment by ArneVogel** [comment]
No I had not updated the CSS. With the newest version of chessground.css the last bug was fixed, but I still can not make moves on mobile.

**Comment by niklasf** [comment]
Mhh ... that's surprising. Previously I couldn't make moves on https://listudy.org/study/KQppEyi with my mobile device. But now, after refreshing, it's working for me.

**Comment by ArneVogel** [comment]
I am trying it on firefox mobile. When I press on the board the arrow indicating the move goes away but the "points" indicating the legal moves dont appear. They also dont appear when I press down for longer. Pressing on the piece and then on the position I know it should go doesnt move it.

**Comment by niklasf** [comment]
Actually I can reproduce the issue sometimes.

I found one potential issue in the debugger. `getChessGroundConfig` is called with `orientation` 0, but movable.color and orientaton are supposed to be `'white'` or `'black'`.
