### ISSUE TITLE
Chessground broken between version 7.5.1 and 7.6.0

### ISSUE THREAD

**Issue by ArneVogel** [ornicar/chessground#96]
With version 7.6.0 and upwards I get this for a previously working config: https://i.imgur.com/ON2PPda.png

No console output or exceptions. The only thing I am changing for the break is the version number in the package.json

**Comment by Simbaclaws** [comment]
I'm experiencing the exact same thing.

**Comment by gbtami** [comment]
The markup changed to fix some lichess v2 issues. If you want to use 7.6.x I suggest to take a look at https://github.com/niklasf/syzygy-tables.info/commit/f7e35b0fe88307be0c8256bc1d6ba854c28dc9cd
